name: C/C++ CI

on:
  push:
    branches: [ main, master, add-github-action-for-CI ]
  pull_request:
    branches: [ main, master, add-github-action-for-CI ]

env:
  V: 1

jobs:
  buildx:

    runs-on: ${{ matrix.os }}

    name: '${{ matrix.os }} buildx'

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:

      - uses: actions/checkout@v2

      - name: 'Install Software (Linux)'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install autopoint gettext doxygen graphviz ${{ matrix.compiler }}

      - name: 'Install Software (MacOS)'
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install automake doxygen graphviz

      - name: 'autoreconf'
        run: autoreconf -vis .

      - name: 'configure'
        run: ./configure

      - name: 'make'
        run: make

      - name: 'make check'
        run: make check

      - name: 'make distcheck'
        run: make distcheck

      - name: 'dist tarball content'
        run: for tarball in *.tar.*; do tar tvf "$tarball"; break; done

  windows-build:
    runs-on: windows-latest

    # See https://github.com/msys2/setup-msys2

    strategy:
      # fail-fast: false
      matrix:
        include:
          - { sys: mingw32, env: i686 }
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
          - { sys: clang64, env: clang-x86_64 } # Experimental!

    name: 'MSYS2 ${{ matrix.sys }} build'

    env:
      MINGW_ARCH: ${{ matrix.sys }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: 'cmd shell environment info'
        shell: cmd
        run: |
          path
          echo %PATH%
          set

      - name: 'git config'
        run:  git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: '${{ matrix.sys }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            git
            autoconf
            automake
            diffutils
            gettext-devel
            intltool
            libtool
            make
            patchutils
            pkgconf
            doxygen
            zip
            mingw-w64-${{ matrix.env }}-graphviz
            mingw-w64-${{ matrix.env }}-gcc

      - name: '${{ matrix.sys }} autoreconf'
        run: autoreconf -vis .

      - name: '${{ matrix.sys }} configure'
        run: ./configure

      - name: '${{ matrix.sys }} make'
        run: make

      - name: '${{ matrix.sys }} make check'
        run: make check

      - name: '${{ matrix.sys }} make distcheck'
        run: make distcheck

      - name: '${{ matrix.sys }} dist tarball content'
        run: for tarball in *.tar.*; do tar tvf "$tarball"; break; done
